### ISSUE TITLE
Project-Id-Version as argument

### ISSUE THREAD

**Issue by c50** [c50/po-xls-for-Drupal#5]
It would be nice to adapt "Project-Id-Version: Drupal core (8.8.0-rc1)\n" to our projects passing arguments to the script like:
- module (e.g. Futurium)
- version. (e.g. 1.0.0-beta1)

Such a way we can batch all language at once, name the files as e.g. module_name.pt-pt.po

**Comment by madewild** [comment]
Fixed in #6
