### ISSUE TITLE
Check to escape characters?

### ISSUE THREAD

**Issue by c50** [c50/po-xls-for-Drupal#7]
@madewild  in all languages we have that issue >  [error]  Import of string "Kirjoita sisällön nimen alku, jotta voit valita sen. Voit kirjoittaa myös sisäisen polun (esim. /node/add) tai lisätä ulkopuolisen URL-osoitteen (esim. http://esimerkki.com). Kirjoittamalla <front> voit tehdä linkin etusivulle." was skipped because of disallowed or malformed HTML.

**Comment by madewild** [comment]
I think the `<front>` variable is the culprit, it's misinterpreted as html markup by the validator. Cf. https://validator.w3.org/ : 

`Error: Element front not allowed as child of element body in this context.`
`Error: Unclosed element front.`

**Comment by c50** [comment]
Ok @madewild, we need to take that in account in the next translation request. <front> is supposed here to be the link to the site front-page. @madewild
